steps:
  - name: build
    image: maven:3.8.1-openjdk-17
    environment:
      WOODPECKER_NOTIFY_DISCORD_ID:
        from_secret: WOODPECKER_NOTIFY_DISCORD_ID
      WOODPECKER_NOTIFY_DISCORD_TOKEN:
        from_secret: WOODPECKER_NOTIFY_DISCORD_TOKEN
    commands:
      - echo "start run the build step "
      - echo $${WOODPECKER_NOTIFY_DISCORD_ID}
      - echo $${WOODPECKER_NOTIFY_DISCORD_TOKEN}
    when:
      event: pull_request

  - name: compile
    image: maven:3.8.1-openjdk-17
    commands:
      - mvn clean
      - mvn compile
      - echo "compile finish"
    when:
      event: pull_request

  - name: spotbugs
    image: maven:3.8.1-openjdk-17
    commands:
      - mvn clean
      - mvn compile
      - mvn spotbugs:check -Dspotbugs.excludeFilterFile=./findbugs-exclude.xml #exclude bug list
    when:
      event: pull_request

  - name: pmd
    image: maven:3.8.1-openjdk-17
    commands:
      - mvn clean
      - mvn compile
      - mvn pmd:pmd
    when:
      event: pull_request

  - name: docker-build-push
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: image.nexus.service.ms-search.us
      repo: ms_search_server
      tags: ${CI_COMMIT_SHA}
      cache: true
      skip_tls_verify: false
      build_args:
        - COMMIT_SHA=${CI_COMMIT_SHA}
        - COMMIT_AUTHOR_EMAIL=${CI_COMMIT_AUTHOR_EMAIL}
      username:
        from_secret: nexus_username
      password:
        from_secret: nexus_password
    when:
      event:
        - push
        - tag
        - pull_request

  - name: comment-pr-tag
    image: alpine/httpie
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - >
        http --ignore-stdin POST
        "https://api.github.com/repos/${CI_REPO}/issues/${CI_COMMIT_PULL_REQUEST}/comments"
        "Authorization: token $${GITHUB_TOKEN}"
        "Accept: application/vnd.github.v3+json"
        body="Docker image built and pushed:\n\`image.nexus.service.ms-search.us/ms_search_server:${CI_COMMIT_SHA}\`"
    when:
      event: 
        - pull_request

  - name: notify
    image: appleboy/drone-discord
    settings:
      webhook_id: 
        from_secret: woodpecker_notify_discord_id
      webhook_token: 
        from_secret: woodpecker_notify_discord_token
      avatar_url: https://woodpecker-ci.org/img/logo.svg
      link_names: true
      template: "CI  {{build.status}} for {{repo.owner}}/{{repo.name}}"
    when:
      event:
        - pull_request
      status:
        - failure
        - success
