steps:
  build:
    image: maven:3.8.1-openjdk-17
    commands:
      - echo "start run the build step "
      - echo $${WOODPECKER_NOTIFY_DISCORD_ID}
      - echo $${WOODPECKER_NOTIFY_DISCORD_TOKEN}
    secrets: [WOODPECKER_NOTIFY_DISCORD_ID, WOODPECKER_NOTIFY_DISCORD_TOKEN]

    when:
      event: pull_request
  compile:
    image: maven:3.8.1-openjdk-17
    commands:
      - mvn clean
      - mvn compile
      - echo "compile finish"
    when:
      event: pull_request

  spotbugs:
    image: maven:3.8.1-openjdk-17
    commands:
      - mvn clean
      - mvn compile
      - mvn spotbugs:check -Dspotbugs.excludeFilterFile=./findbugs-exclude.xml #exclude bug list
    when:
      event: pull_request

  pmd:
    image: maven:3.8.1-openjdk-17
    commands:
      - mvn clean
      - mvn compile
      - mvn pmd:pmd
    when:
      event: pull_request


#  test:
#    image: maven:3.8.1-openjdk-17
#    commands:
#      - mvn test
  docker-build-push:
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: image.nexus.service.ms-search.us
      repo: ms_search_server
      tags: ${CI_COMMIT_SHA}
      cache: true
      skip_tls_verify: false # set to true for testing registries ONLY with self-signed certs
      build_args:
        - COMMIT_SHA=${CI_COMMIT_SHA}
        - COMMIT_AUTHOR_EMAIL=${CI_COMMIT_AUTHOR_EMAIL}
      username:
        from_secret: nexus_username
      password:
        from_secret: nexus_password
    when:
      event:
        - push
        - tag
        - pull_request

  comment-pr-tag:
    image: alpine/httpie
    commands:
      - >
        http --ignore-stdin POST
        "https://api.github.com/repos/${CI_REPO}/issues/${CI_COMMIT_PULL_REQUEST}/comments"
        "Authorization: token $${GITHUB_TOKEN}"
        "Accept: application/vnd.github.v3+json"
        body="Docker image built and pushed:\n\`image.nexus.service.ms-search.us/ms_search_server:${CI_COMMIT_SHA}\`"
    secrets: [GITHUB_TOKEN]
    when:
      event: pull_request

# 設定通知，discord 作為通知工具
  notify:
    image: appleboy/drone-discord
    settings:
      webhook_id: 
        from_secret: woodpecker_notify_discord_id
      webhook_token: 
        from_secret: woodpecker_notify_discord_token
      avatar_url: https://woodpecker-ci.org/img/logo.svg
      link_names: true
      template: >
    when:
      event:
        - pull_request
      status:
        - failure
        - success
