steps:
  build:
    image: maven:3.8.1-openjdk-17
    commands:
      - echo "start run the build step "
    when:
      event: pull_request
  compile:
    image: maven:3.8.1-openjdk-17
    commands:
      - mvn clean
      - mvn compile
      - echo "compile finish"
    when:
      event: pull_request
#  test:
#    image: maven:3.8.1-openjdk-17
#    commands:
#      - mvn test

# 設定通知，discord 作為通知工具
  notify:
      image: appleboy/drone-discord
      settings:
        webhook_id: 1261954462457663509
        webhook_token: r_jyeEffW5fruirutU1k54Wzes__hn99klsFNUweSbHR8TuqO09cJ6r5hLxs1YedTH1A
        avatar_url: https://woodpecker-ci.org/img/logo.svg
        link_names: true
#        message: >
#          {{#success build.status}}
#            [PR] {{repo.name}}/#{{build.number}} succeeded
#            Author: {{build.author}} {{build.event}} to {{build.branch}}
#            CI Link: {{build.link}}
#            GIT Link: https://github.com/{{repo.owner}}/{{repo.name}}/pull/{{build.pull}}
#            Message: {{build.message}}
#          {{else}}
#            [PR] {{repo.name}}/#{{build.number}} fail.
#            Author: {{build.author}} {{build.event}} to {{build.branch}}.
#            CI Link: {{build.link}}
#            GIT Link: https://github.com/{{repo.owner}}/{{repo.name}}/pull/{{build.pull}}
#            Message: {{build.message}}
#          {{/success}}
        message: >
           {{#success build.status}}
             build {{build.number}} succeeded. Good job.
           {{else}}
             build {{build.number}} failed. Fix me please.
           {{/success}}
      when:
        event:
          - pull_request
        status:
          - failure
          - success
