steps:
  build:
    image: maven:3.8.1-openjdk-17
    commands:
      - echo "start run the build step "
    when:
      event:
        - pull_request
  compile:
    image: maven:3.8.1-openjdk-17
    commands:
      - mvn clean
      - mvn compile
      - echo "compile finish"
    when:
      event: pull_request
#  test:
#    image: maven:3.8.1-openjdk-17
#    commands:
#      - mvn test

# 設定通知，discord 作為通知工具
  notify:
    image: appleboy/drone-discord
    secrets: [WOODPECKER_NOTIFY_DISCORD_ID, WOODPECKER_NOTIFY_DISCORD_TOKEN]
    settings:
      webhook_id: ${WOODPECKER_NOTIFY_DISCORD_ID}
      webhook_token: ${WOODPECKER_NOTIFY_DISCORD_TOKEN}
      avatar_url: https://woodpecker-ci.org/img/logo.svg
      link_names: true
      template: >
    when:
      event:
        - pull_request
      status:
        - failure
        - success