apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-search-engine
  labels:
    app: {{ .Values.app.appMsSearchServer.name }}
spec:
  ingressClassName: {{ .Values.app.appMsSearchServer.name }}
  rules:
    - host: ms-search.server.local
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.app.appMsSearchServer.name }}
                port:
                  number: {{ .Values.service.port }}

